depthchargectl: Avoid None as board codename
If a config section doesn't have a codename, we get an error when
trying to propagate it into our ConfigParser instances for subcommand
calls to use:

  option values must be strings
  Traceback (most recent call last):
    File "/home/alpernebbi/git/github.com/alpernebbi/depthcharge-tools/depthcharge_tools/utils/argparse.py", line 936, in main
      output = command(__raise_CommandExit=True, **kwargs)
    File "/home/alpernebbi/git/github.com/alpernebbi/depthcharge-tools/depthcharge_tools/utils/argparse.py", line 855, in __normal_call
      retval = inst(*args, **kwargs)
    File "/home/alpernebbi/git/github.com/alpernebbi/depthcharge-tools/depthcharge_tools/utils/argparse.py", line 789, in __call__
      getattr(self, grp_name, None)
      ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
    File "/home/alpernebbi/git/github.com/alpernebbi/depthcharge-tools/depthcharge_tools/utils/argparse.py", line 529, in __get__
      outputs = func(*inputs.args, **inputs.kwargs)
    File "/home/alpernebbi/git/github.com/alpernebbi/depthcharge-tools/depthcharge_tools/depthchargectl/__init__.py", line 370, in config_options
      self.config.update({
      ~~~~~~~~~~~~~~~~~~^^
          'board': self.board.codename if self.board else "none",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ...<6 lines>...
          'zimage-initramfs-hack': str(self.zimage_initramfs_hack),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      })
      ^^
    File "<frozen _collections_abc>", line 991, in update
    File "/usr/lib/python3.13/configparser.py", line 1291, in __setitem__
      self._parser._validate_value_types(option=key, value=value)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.13/configparser.py", line 1231, in _validate_value_types
      raise TypeError("option values must be strings")
  TypeError: option values must be strings

Cast it to a string to defend against this, but that gives us "None",
so also normalize it to "none" in the Board object.

Signed-off-by: Alper Nebi Yasak <alpernebiyasak@gmail.com>