utils: pathlib: Avoid returning empty decompression output
We try to decompress input files with the usual compression tools to use
the decompressed versions which would be the actual bootable artifacts.
If the lzma Debian package is installed, that one provides the lzma
compressor instead of the xz-utils package, and causes `depthchargectl
build` to fail with an error:

  $ depthchargectl build --board amd64-generic -vvv
  [...]
  Failed while creating depthcharge image.
  Traceback (most recent call last):
  [...]
  File "/usr/lib/python3/dist-packages/depthcharge_tools/mkdepthcharge.py", line 960, in __call__
    with vmlinuz.open("r+b") as f, mmap(f.fileno(), 0) as data:
                                   ~~~~^^^^^^^^^^^^^^^
  ValueError: cannot mmap an empty file
  [...]

Ultimately, it's because `lzma -d` returns a zero exit status for certain
files even though it outputs nothing:

  $ head -c18 "/boot/vmlinuz-$(uname -a)" | xxd
  00000000: 4d5a 0000 0000 0000 0000 0000 0000 0000  MZ..............
  00000010: 0000                                     ..

  $ head -c18 "/boot/vmlinuz-$(uname -a)" | lzma -d; echo $?
  0

Check against empty decompression outputs, consider them not compressed
with that scheme, and so continue trying with other decompressors.
We need to remove the newly created empty file so the next compressor
doesn't throw up a FileExistsError.

Fixes: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1145048
Signed-off-by: Alper Nebi Yasak <alpernebiyasak@gmail.com>